### ISSUE TITLE
Tough as nails Integration

### ISSUE THREAD

**Issue by Dalethium** [GirafiStudios/Waddles#1]
Perhaps (not 100% sure it's needed it but) you could add support for tough as nails -- maybe the penguins won't spawn in the other biomes, but maybe they'll wander out of their native biomes a lot more during winter. 

 (Posted here as requested: https://minecraft.curseforge.com/projects/waddles?comment=13)

**Comment by GirafiStudios** [comment]
I have been thinking about this for a while and decided that it is not a good idea. Making penguins spawn in other biomes, when it is winter in Tough as Nails would be possible. The problem is just that they would still be there in the spring.
Making them wander out of their native biomes, would require some semi-complicated AI. It would also require them to wander in chunks that are not loaded, which is not really possible.
